### ISSUE TITLE
Switching filterchain corrupts first frame

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#46]
When I change the size of the Image in my filterchain, then the first frame is distorted.
I use pl_render_image and only change the size of the input image.

I have attached a Trace of the problem with some comments from me.  The Trace starts with a picture of the szie 1280x720 and then I switch to a new channel with size 720x576. There the first frame is distorted.  The complete Source can be found at: https://github.com/jojo61/vdr-plugin-softhdcuvid
There look at the file video.c and search for PLACEBO. Everything is in ifdef PLACEBO capsuled.
I have disabled my prints but they are still in the souce.
PS: I use your branch master from today

[trace.log.gz](https://github.com/haasn/libplacebo/files/2545826/trace.log.gz)

**Comment by haasn** [comment]
Some comments:

1. You make the assumption that the `pl_buf` for Y and UV will end up in the same memory object (i.e. have the same fd). This is not correct, and destroying + recreating buffers can easily break that assumption as the internal memory allocator spills over into a new VkBuffer.

2. You do a bunch of stuff that very much violates the ABI, like accessing internal fields (->priv) or dropping the `const` qualifier off public structs and mutating them. For example, I saw calls like ` glDrawVkImageNV`. I'm not entirely sure what this call does, but since it isn't synchronized w.r.t the rest of the libplacebo operations on the VkImage this seems like a good candidate for the culprit here. (And actually, lack of synchronization can explain corruption even when using `pl_gpu_finish` or other blocking operations - since the synchronization primitives also take care of image layout transitions and cache coherency)

I'm not entirely sure from the source code why this is needed - but if you need access to the `VkImage` of a `pl_tex`, you need create the VkImage yourself, use `pl_vulkan_wrap` to turn it into a `pl_tex`, and then use `pl_vulkan_hold` and `pl_vulkan_release` to acquire/release the underlying VkImage in order to synchronize it w.r.t the cuda operations you want to perform on it. This also requires creating a VkSemaphore pair and importing it into the CUDA API (e.g. via fd) so you can synchronize it.

And yes, that's a lot of annoying boilerplate to actually do - which is why going via a shared pl_buf is the vastly easier option here. Maybe you can do that for your glDrawVkImageNV call as well.

**Comment by jojo61** [comment]
Ok

1. I used just one FD out of convinience, thats easy to change it is already in the sources.

2. Before implementing you library everything was based on opengl and so it was easy to stick with it and just copy the result from the rendering via glDrawVkImageNV  onto the opengl Framebuffer.. Nvidia officially supports this mixed operation. 

You are right that I made a shortcut to get access to the VkImage and I will look into you suggestion to get hold of my own one. That is btw also recommended by Nvidia together with the Semaphores. I just did not see how to archive this. I will also go back to the const qualifiers. I had no intention to break that.

Thanks for you help.

**Comment by haasn** [comment]
It's probably reasonable for us to make the VkImage interop API easier by providing a way to export the VkImage of an internally allocated `pl_tex` directly? That way you will at least not have to care about memory management and the messy details of VkImage creation.

**Comment by jojo61** [comment]
That would make living easier and make more sense in the way that the library should cover the VkImage creation and management.  That way I do not need to mess with semaphores and that stuff.
But the VkImage should be accessible on the Device and not needed to be copied to host RAM.

But after all i'm not sure that this is the main problem with the render chain.   When I change the size I get a result where the UV plane from the previous plane is used. So I have an Image with the colors from the previous Image. This looks to me that there is something wrong with the Conversion from YUV to RGB at the beginning of the render chain.  Thats for the first frame only..

One more thing.
Some of the filters return a black Image eg. ewa_lanczos when used in pl_render_image.

**Comment by haasn** [comment]
@jojo61 I pushed d777666 to master, which allows you to gain access to the `VkImage` from a libplacebo-allocated `pl_tex`. You can try doing this, in combination with `pl_vulkan_hold` and `pl_vulkan_release`, to do your direct texture interop.

That said, I'm not entirely sure if this is useful. It's possible you need image usage flags that we don't provide upon creation, or that you lack other metadata about the image. Also, @philipl was adamant about there being a texture interop driver bug in nvidia's cuda implementation, but I'm not sure exactly what sorts of issues that caused. (Crash? Frame corruption?)

**Comment by haasn** [comment]
> That way I do not need to mess with semaphores and that stuff.

You still need to do this even if libplacebo allocates the VkImage for you. Unless we add CUDA interop to libplacebo itself, *something* has to synchronize the access to the image between cuda and libplacebo.

> But after all i'm not sure that this is the main problem with the render chain. When I change the size I get a result where the UV plane from the previous plane is used. So I have an Image with the colors from the previous Image. This looks to me that there is something wrong with the Conversion from YUV to RGB at the beginning of the render chain. Thats for the first frame only..

If the Y plane is correct but the UV planes are not, then that indeed shifts the attention away from this VkImage interaction and towards the texture contents / upload itself. Either the contents of the buffer are wrong at the point in time of the upload, or the image parameters are somehwo not correct for a frame. It would probably be a good idea to step through the size change in gdb and get a print-out of the entire `pl_image` struct you pass to `pl_render_image` for the frame preceding, immediately after, and subsequently following the resize.

**Comment by jojo61** [comment]
> @jojo61 I pushed d777666 to master, which allows you to gain access to the VkImage from a >libplacebo-allocated pl_tex. You can try doing this, in combination with pl_vulkan_hold and >pl_vulkan_release, to do your direct texture interop.

Ok that sounds fine and I will try to use you changes. Should  not be difficult to enclose the usage of the VkImage  with pl_vulkan_hold and pl_vulkan_release. I will provide feedback if this solves the issue with the compute shaders.  
Concerning the problem with the UV plane I will dump the planes before calling pl_render_image to be sure that the content is correct in the first place.

@philipl  I have seen that you close the fd of the buffers in mpv. You should not do this. Afterwards cuda is completly broken. It took me 6 hours of debugging until I found a NVIDIA memo with says that you should not touch the fd anymore after it has been given to cuda.

**Comment by philipl** [comment]
@jojo61 That should not be the case. If you look carefully, the hwdec_cuda code only closes the fd if the fd was not successfully imported. I did read the doc saying that ownership is transferred on import, but equally, it is not transferred if the import fails and the vulkan side won't clean up the fd either.

**Comment by jojo61** [comment]
The delayed UV frame seems not to happen anymore when I use pl_vulkan_hold.....

But the compute shaders still do not work. I use the following code. Maybe you see my mistake:

    if (!pl_render_image(p->renderer, &decoder->pl_images[current], &target, &render_params)) {
              Fatal(_("Failed rendering frame!\n"));
    }
	pl_gpu_finish(p->gpu);
	Image = pl_vulkan_unwrap(p->gpu, target.fbo,0,0);  // GetImage from texture
	pl_vulkan_hold(p->gpu,target.fbo, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, VK_ACCESS_MEMORY_READ_BIT, p->sig_in);	 // get it for me	
	glWaitVkSemaphoreNV((GLuint64)p->sig_in);

    	glDrawVkImageNV((GLuint64)Image, 0, dst_video_rect.x0,dst_video_rect.y0,dst_video_rect.x1, dst_video_rect.y1, 0,0,1,1,0);	
	GlxCheck();
	pl_vulkan_release(p->gpu, target.fbo,0,0,0);  // give it back
	pl_tex_destroy(p->gpu,&target.fbo);  // destroy texture

**Comment by haasn** [comment]
Does libplacebo log anything? Try enabling vulkan instance debugging.

Also, it would be better for performance to drop the `pl_gpu_finish` and `GlxCheck()` and instead signal a VkSemaphore from the GL side as well (then use that when doing `pl_vulkan_release`). But that shouldn't cause the black screen issue.

Also, I'm pretty sure the image layouts / access modes you specified for `hold` and `release` are wrong, but the nvidia documentation for that GL extension doesn't clarify what the correct values should be.

**Comment by jojo61** [comment]
When I enable vulkan instance debugging the program will crash in glWaitVkSemaphoreNV.
When I disable the complete part from hold to release and enable debug I see some strange debug infos before the pl_render_image

error: vk [ParameterValidation] 461558787: vkCmdPipelineBarrier: value of srcStageMask must not be 0. The spec valid usage text states 'srcStageMask must not be 0' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-srcStageMask-requiredbitmask) (obj 0x0 (unknown object), loc 0x2ee)
error: vk [ParameterValidation] 461558787: vkCmdPipelineBarrier: value of srcStageMask must not be 0. The spec valid usage text states 'srcStageMask must not be 0' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-srcStageMask-requiredbitmask) (obj 0x0 (unknown object), loc 0x2ee)
error: vk [ParameterValidation] 461404163: vkCmdPipelineBarrier: value of dstStageMask must not be 0. The spec valid usage text states 'dstStageMask must not be 0' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-dstStageMask-requiredbitmask) (obj 0x0 (unknown object), loc 0x2ee)
 warn: vk [MEM] 15: vkCmdCopyBufferToImage(): Cannot read invalid region of memory allocation 0x3f for bound Buffer object 0x3e, please fill the memory before using. (obj 0x3f (VkDeviceMemory), loc 0x17f)
 warn: vk [MEM] 15: vkCmdCopyBufferToImage(): Cannot read invalid region of memory allocation 0x3f for bound Buffer object 0x3e, please fill the memory before using. (obj 0x3f (VkDeviceMemory), loc 0x17f)

**Comment by jojo61** [comment]
I think I will go the way with a swapchain and a vulkan window. This seems more natural and should avoid the problems  I currently have with rendering on a opengl window.

**Comment by haasn** [comment]
Good catch. The queue family ownership transfer was not up to spec. This should fix it:

```
commit fe48991b18f3ad15ccbfa45e67c5566f2a595e85
Author: Niklas Haas <git@haasn.xyz>
Date:   Mon Nov 12 21:17:15 2018 +0100

    vulkan: use the correct pipeline stage for ownership transfers
    
    While the access mask is ignored for a queue family ownership transfer,
    the pipeline stage is not. For lack of anything sane to put here, just
    use TOP/BOTTOM.

diff --git a/src/vulkan/gpu.c b/src/vulkan/gpu.c
index 3fcd245..9f72eba 100644
--- a/src/vulkan/gpu.c
+++ b/src/vulkan/gpu.c
@@ -1120,7 +1120,12 @@ static bool vk_buf_export(const struct pl_gpu *gpu, const struct pl_buf *buf)
         return false;
     }
 
-    buf_barrier(gpu, cmd, buf, 0, 0, 0, buf->params.size, true);
+    // For the queue family ownership transfer, we can ignore all pipeline
+    // stages since the synchronization via fences/semaphores is required
+    buf_barrier(gpu, cmd, buf, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0,
+                0, buf->params.size, true);
+    buf_vk->current_stage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
+
     vk_submit(gpu);
     return vk_flush_commands(vk);
 }
```

The other one might be a bug in the validation layers - it probably thinks that nothing has written to the VkDeviceMemory, but it doesn't know about the fact that CUDA wrote to that memory (externally).

> I think I will go the way with a swapchain and a vulkan window. This seems more natural and should avoid the problems I currently have with rendering on a opengl window.

Yes, that would probably be easier than trying to properly synchronize vulkan and opengl.

**Comment by jojo61** [comment]
When I use a swapchain then all filters are working correct. So I will close this isse.

**Comment by haasn** [comment]
@jojo61 Btw, we now added (on `master`) a new `pl_sync` abstraction and a new function `pl_tex_export` which can be used to do CUDA texture interop directly. (Assuming you're on a new enough nvidia driver so that this actually works)

This should be much easier than the old API and also easier than manually doing `pl_vulkan_hold/release`. You could give it a try and see if it works for you.

(We also refactored the handle API, so your old shared buffer code will break. Sorry)
