### ISSUE TITLE
Orthogonal scalers output slightly shifted image

### ISSUE THREAD

**Issue by Lypheo** [haasn/libplacebo#72]
Orthogonal scalers output a slightly shifted image compared to both zimg and pl’s polar scalers.
Comparison: https://slow.pics/c/m4489mqo.
This happens both when using the [sampling shaders directly](https://p.kageru.moe/CoFwI1) and when using the [renderer API](https://p.kageru.moe/fNS7Yp).
The shift does not always occur; it appears to be resolution-dependent, but I haven’t been able to identify a clear pattern.

**Comment by haasn** [comment]
Just to be sure, can you use a test pattern that has clearly visible edges? (e.g. downscaling a PNG screenshot where the edges have been marked with 1-pixel wide rainbow stripes so we can clearly see where the cutoff is)

It may also help to use e.g. nearest neighbour sampling for these tests, or perhaps bilinear (to avoid possible rounding issues nearest neighbour).

Also, if it only happens for some resolutions, can you attach a screenshot and width/height combination that reproduces the shift? I'll try reproducing it.

**Comment by haasn** [comment]
Also, does it still happen if you set `params->no_widening`? (Although I understand that this will make it hard to tell based on the fact that it will introduce horrible aliasing)

**Comment by Lypheo** [comment]
Not sure if this more helpful, but here’s a 720p -> 711p downscale: https://slow.pics/c/KFcZ3FbT ([Source](https://www.rtings.com/images/test-materials/2017/chroma-444.png)).

Here’s the same with bilinear: https://slow.pics/c/AdDVEbHj
>Also, does it still happen if you set params->no_widening? (Although I understand that this will make it hard to tell based on the fact that it will introduce horrible aliasing)

That fixes it indeed.

**Comment by haasn** [comment]
Okay, I can reproduce the issue on my end.

**Comment by haasn** [comment]
Okay the issue with nearest neighbour sampling is fundamental to the fact that nearest neighbour sampling is a bit special (the 'discontinuity' makes it behave strangely). I'll solve that issue by making nearest neighbour non-resizeable. However, it doesn't change the fact that there's a shift when resizing the kernel.

I'll look into this more tomorrow.

**Comment by haasn** [comment]
Should be fixed. Thanks for catching this. It's a rather embarrassing bug to have had around for so long, given that orthogonal downsampling is such a common thing to be doing, but fortunately we were saved in that the most common cases (e.g 4K -> 1080p) were clean enough multiples to not hit this bug.

**Comment by Lypheo** [comment]
Thank you for taking the time to investigate.

I ran into another issue, but since I’m not entirely sure it’s a bug on your end, I don’t wanna open another issue for it:
Since upgrading from PL_API_VER = 31 to git master, I’ve been getting this assertion error:
```
Assertion failed: target_w > 0 && target_h > 0, file ../src/renderer.c, line 943
```
when using the renderer API (unconditionally, even on no-ops). Any chance this is a regression introduced by 06791c9e38225ac5b0855e3c6b7f6752d350622f?

**Comment by haasn** [comment]
@Lypheo Yep, simple oversight. Fixed in aca6cac.

**Comment by Lypheo** [comment]
Thank you. 
One last question on an unrelated note, if I may: What’s the current state of the custom_shaders branch. Is it usable at all yet?

**Comment by haasn** [comment]
It still needs to be hooked up with the `pl_renderer` after the plane state refactors. It should be relatively straightforward. I'll do it after I wake up I guess.

Then it needs testing, which depending on how many problems I run into will take god knows how long. In theory this branch was completed in the past once before but I ran into bugs when testing it which were what prompted me to leave it sitting for another few months until I got around to doing the plane state refactor...

**Comment by Lypheo** [comment]
I see, thank you. Looking forward to its completion. :>

**Comment by Lypheo** [comment]
@haasn actually, doesn’t seem like your fix works. It only fixes some scaling ratios, but the bug still occurs for others. I poked compute_row a little and it appears like changing https://github.com/haasn/libplacebo/blob/0f27cf689d7ba35b0a684120467d20991241748a/src/filters.c#L109-L109 to
```C
        double x = offset - (i - ceil(f->radius) + 1);
```
fixes it.

**Comment by haasn** [comment]
Huh. `ceil(f->radius)` is suspiciously close to `(f->row_size / 2)`, which is what the code was before the patch, since `f->row_size = ceil(f->radius * 2.0)`. 

I guess the way the code was originally written wasn't too far off the mark (the intent being to find the "center" of the row, at least in terms of how it's going to be convolved), but the issue was failing to account for the fact that the caller effectively rounds to individual pixels, rather than multiples of two.

I'll change it again. Hopefully for the last time.

**Comment by haasn** [comment]
@Lypheo The code you have renders the right result but is also shifted by 1 pixel to the left/right compared to IM for me. :thinking:

**Comment by haasn** [comment]
Inspecting the pixels more closely, the `ceil(f->radius)` case matches the output of IM but is shifted, whereas `f->radius` is not shifted but also deviates very slightly from the IM result.

**Comment by haasn** [comment]
I think the proper solution is to revert the code back to `f->row_size / 2` and instead change `f->row_size = ceil(f->radius) * 2.0;`

**Comment by haasn** [comment]
I also noticed that my addition of a nearest neighbour filter effectively accidentally ended up disabling anti-aliasing for a bunch of other filters as well (e.g. mitchell). Decided to just revert that commit. To get proper nearest-neighbour downsampling, use `box` *and* also disable anti-aliasing. I won't add some hack / special-case to disable it automatically. If the user wants aliasing, the user can request aliasing.

**Comment by Lypheo** [comment]
Thanks, can confirm output now matches zimg for all scaling rations.
